DROP TABLE PRODUTO IF EXISTS;

CREATE TABLE PRODUTO  (
    gtin 	VARCHAR(13) NOT NULL,
    nome 	VARCHAR(200),
    PRIMARY KEY (gtin)
);

DROP TABLE FORNECEDOR IF EXISTS;

CREATE TABLE FORNECEDOR  (
    cnpj 	VARCHAR(18) NOT NULL,
    nome 	VARCHAR(200) NOT NULL,
    PRIMARY KEY (cnpj)
);

DROP TABLE PRECO_FORNECEDOR IF EXISTS;

CREATE TABLE PRECO_FORNECEDOR  (
    id                  INTEGER NOT NULL IDENTITY,
    preco 	            DECIMAL(12,2),
    quantidade_minima   INTEGER,
    PRIMARY KEY (id)
);

DROP TABLE PEDIDO IF EXISTS;

CREATE TABLE PEDIDO  (
    id              INTEGER NOT NULL IDENTITY,
    fornecedor_cnpj VARCHAR(18) NOT NULL,
    PRIMARY KEY (id),
	  FOREIGN KEY (fornecedor_cnpj) REFERENCES FORNECEDOR(cnpj)
);

DROP TABLE ITEM_PEDIDO IF EXISTS;

CREATE TABLE ITEM_PEDIDO  (
    id              INTEGER NOT NULL IDENTITY,
    quantidade      INTEGER NOT NULL,
    preco 	        DECIMAL(12,2) NOT NULL,
    total           DECIMAL(12,2) NOT NULL,
    gtin            VARCHAR(13) NOT NULL,
    PRIMARY KEY (id),
	  FOREIGN KEY (gtin) REFERENCES PRODUTO(gtin)
);

DROP TABLE PEDIDO_ITENS IF EXISTS;

CREATE TABLE PEDIDO_ITENS (
  pedido_id INTEGER NOT NULL,
  itens_id  INTEGER NOT NULL,
  FOREIGN KEY (pedido_id) REFERENCES PEDIDO(id),
  FOREIGN KEY (itens_id) REFERENCES ITEM_PEDIDO(id)
);

DROP TABLE FORNECEDOR_PRECOS IF EXISTS;

CREATE TABLE FORNECEDOR_PRECOS (
  fornecedor_cnpj VARCHAR(18) NOT NULL,
  precos_id       INTEGER NOT NULL,
  FOREIGN KEY (fornecedor_cnpj) REFERENCES FORNECEDOR(cnpj),
  FOREIGN KEY (precos_id) REFERENCES PRECO_FORNECEDOR(id)
);

